package main

var reaganFacts = []string{
	"Reagan opposed the Civil Rights Act of 1964 and the Voting Rights Act of 1965.",
	"On August 5, 1981, Reagan fired 11,359 striking air traffic controllers and banned them from federal employment for life.",
	"Reagan's PATCO crackdown in 1981 is credited with emboldening corporate America to permanently replace striking workers.",
	"Reagan nearly tripled the national debt, from $998 billion in 1981 to $2.86 trillion in 1989.",
	"Reagan initially opposed making MLK Day a federal holiday, questioning whether King was 'important enough.'",
	"Reagan didn't publicly say the word \"AIDS\" until September 1985. By then, over 12,000 Americans had already died.",
	"Reagan cut funding for drug treatment programs while simultaneously massively expanding enforcement.",
	"Reagan raised taxes 11 times after his initial 1981 cut, including the largest peacetime tax increase in history in 1982.",
	"Reagan's deregulation contributed to the Savings & Loan crisis, which cost taxpayers $132 billion in bailouts.",
	"In 1971, Reagan called African UN diplomats 'monkeys' in a recorded call with Nixon. The tape was released in 2019.",
	"Reagan's first major speech on AIDS was May 31, 1987 - six years into the epidemic. Nearly 21,000 Americans were already dead.",
	"Reagan's War on Drugs increased the federal prison population from 24,000 in 1980 to over 100,000 by 1989.",
	"Reagan removed the solar panels Jimmy Carter installed on the White House roof in 1986.",
	"Reagan vetoed the Comprehensive Anti-Apartheid Act of 1986.",
	"After Reagan fired PATCO air traffic controllers in 1981, it took nearly a decade to restore staffing levels.",
	"Reagan's 1980 campaign launched in Philadelphia, MS (where three civil rights workers were murdered in 1964) with mentions of \"states' rights.\"",
	"Reagan closed psychiatric hospitals as California governor in 1967, contributing directly to modern homelessness in the state.",
	"When asked about AIDS in 1982, Reagan's press secretary Larry Speakes laughed and called it 'the gay plague.'",
	"Reagan's administration trained and funded the Salvadoran military, which massacred over 800 civilians at El Mozote in 1981.",
	"The 1986 Anti-Drug Abuse Act, signed by Reagan, created the 100:1 crack vs. powder cocaine sentencing disparity.",
	"Reagan's EPA budget was cut by 22%. Staff was reduced by 20%.",
	"In 1981, Reagan claimed trees cause more pollution than automobiles.",
	"Reagan's Interior Secretary James Watt said he didn't worry about protecting the environment because Jesus would return soon.",
	"In 1961, Reagan recorded an LP warning that Medicare would lead to socialism and the end of freedom in America.",
	"Reagan eliminated the FCC Fairness Doctrine in 1987, enabling the rise of one-sided partisan talk radio.",
	"Reagan's HUD Secretary Samuel Pierce oversaw a scandal where housing funds were steered to Republican donors. 16 officials were convicted.",
	"In 1981, Reagan's administration tried to classify ketchup as a vegetable to cut school lunch costs.",
	"Reagan slashed federal housing assistance by 75%, contributing directly to the 1980s homelessness crisis.",
	"The poverty rate rose from 11.7% to 15.2% during Reagan's first term.",
	"Reagan cut the top marginal tax rate from 70% to 28%, the largest tax cut for the wealthy in American history.",
	"Real wages for the bottom 50% of workers declined during the Reagan years despite GDP growth.",
	"Reagan didn't just fire the PATCO strikers — he decertified the entire union and banned the workers from federal jobs for life.",
	"PATCO had endorsed Reagan in the 1980 election. He crushed them anyway.",
	"After Reagan's PATCO bust, the use of permanent replacement workers by private employers increased dramatically throughout the 1980s.",
	"Reagan stacked the National Labor Relations Board with anti-union appointees. Under his NLRB, enforcement of employer violations dropped sharply.",
	"Reagan's NLRB Chairman Donald Dotson openly stated that collective bargaining \"destroys individual freedom.\"",
	"Before Reagan, it was rare for employers to permanently replace strikers. After PATCO, it became standard corporate practice.",
	"Under Reagan's NLRB, complaints settled in favor of laborers dropped by more than 50%.",
	"Reagan closed one-third of OSHA field offices and cut staff by over 25%.",
	"Under Reagan, OSHA penalties against employers dropped by nearly 75%.",
	"Reagan's OSHA shifted from enforcement to \"voluntary compliance\", preferring that employers police themselves.",
	"Union membership fell from 23% to 16% of the workforce during Reagan's presidency.",
	"Reagan made efforts to weaken child labor laws and create a sub-minimum wage for young workers.",
	"Reagan's 1982 Bus Regulatory Reform Act led directly to the 1983 Greyhound strike, which ultimately decimated bus driver unions.",
}

var transportTrivia = []string{
	"Some early swept-wing jets used stick-force gradients tuned to mask Mach tuck rather than eliminate it aerodynamically.",
	"Certain turbine engines briefly gain surge margin during rapid throttle chops due to compressor unloading.",
	"The first certified autoland systems assumed a failed flare and relied on ground effect to save touchdowns.",
	"In some designs, spoiler panels are aerodynamically blanked at high alpha, reducing roll authority exactly when demanded most.",
	"Cabin pressure relief valves can momentarily open during aggressive pitch changes despite stable differential pressure.",
	"Early FBW test aircraft intentionally injected artificial control lag to preserve pilot “feel” during evaluation.",
	"Certain airliners experience higher brake temperatures after short taxi distances due to carbon brake oxidation inefficiency.",
	"Some yaw dampers apply rudder opposite sensed yaw during turbulence to reduce structural fatigue, foregoing increased comfort in favor of airframe longevity.",
	"Modern turbofan engine EGT and flame depth margins can often be temporarily increased following prolonged cruise power settings.",
	"Several swept-wing aircraft exhibit negative dihedral effect near stall due to spanwise flow reversal.",
	"In some descent regimes, thrust increase can momentarily increase sink rate before pitch coupling stabilizes.",
	"A few certified aircraft produce measurable lift from the fuselage at cruise Mach numbers.",
	"Certain autopilots intentionally fly slightly out of trim to maintain faster control loop response.",
	"Static port errors often reverse sign during sideslip, producing airspeed indications counter to calibration expectations.",
	"Some turbine engines are more resistant to ice crystal icing at high power than at idle due to modern pre-diffuse gas path design.",
	"Early RNAV systems rounded waypoints differently depending on hemisphere, largely due to magnetic model limitations.",
	"In rare cases, thrust reverser deployment reduces yaw moment more than rudder input at high crosswinds.",
	"Certain flight control computers intentionally ignore pilot inputs below a threshold to prevent control \"hunting.\"",
	"Some aircraft exhibit lower buffet onset margins in smooth air than in light turbulence.",
	"Select widebody transport aircraft generate measurable roll from asymmetric engine bleed extraction.",
	"Certain swept-wing jets experience reduced rudder effectiveness before aileron effectiveness at high Mach.",
	"The vertical stabilizer on several large jets produces significant lift during crosswind cruise, negatively affecting stability and requiring additional drag to correct.",
	"Some airliners can momentarily exceed certified control surface rates during law transitions, storing data about these events in periodic health monitoring reports.",
	"Many autothrottle systems will not command full rated thrust unless a specific thrust-rating discrete is latched, regardless of lever position.",
	"Several transport aircraft treat airspeed as a derived parameter, with Mach as the primary controlled variable above crossover altitude.",
	"Thrust reverser position feedback is most commonly validated by *hydraulic pressure decay*, not actual sleeve position.",
	"Brake temperature sensors often lag real rotor temperature by several minutes due to brake mass or materials.",
	"On many jets, the rudder ratio unit schedule is tied to Mach integral rate, not pure Mach value.",
	"Most common IRS alignment errors manifest only during large heading changes at the cardinal magnitude, but not in steady cruise or during small path adjustments.",
	"Transport category electrical load shedding logic frequently prioritizes generator thermal margin over bus voltage stability.",
	"APU fire loops can be powered from non-essential buses, even when protecting essential bleed paths in normal or non-normal scenarios.",
	"Thrust asymmetry detection is often based on N1 divergence rate, not absolute rotor speed mismatch.",
	"The 777 flight controls have three channels with three computing lanes apiece, but design advancements led to *less* overall monitoring to improve dispatch reliability.",
	"Modern flap skew detection logic can be based on time-to-position rather than only comparing absolute symmetry.",
	"Some air data computing relies on smoothing filters that intentionally under-report rapid airspeed changes.",
	"Several ETOPS diversion rules are driven by oil consumption trend analysis, not absolute quantity.",
	"Elevator feel systems can mask excessive hinge moment until hydraulic pressure drops, leading to limits on feel buffering depending on computed surface authority.",
	"Some modern control systems classify instances of yaw damper hardovers as “nuisance” events, unless sustained beyond a timer threshold.",
	"Several competing airliners’ control and core navigation systems share common software libraries designed and backed by NASA.",
	"Bleed air leak detection in advanced transport aircraft can rely on subtleties like temperature *gradient* instead of solely monitoring for exceedance.",
	"Certain overspeed protections are advisory only unless combined with vertical acceleration thresholds, but will still ground an airframe until properly vetted.",
	"Some FCCs will continue using a failed sensor indefinitely if it failed within tolerance and never crossed a fault threshold.",
	"Certain air data computers reject valid inputs during rapid transients because plausibility checks assume steady-state conditions.",
	"Autopilot disengage logic can be masked if the disengage request originates from the same channel commanding engagement.",
	"Some inertial reference systems silently revert to last-known-good bias values during intermittent failures, obtained in health monitoring as \"economic\" category faults.",
	"Certain Mach trim systems continue commanding trim indefinitely despite autopilot disconnect.",
	"In some architectures, a failed watchdog timer resets the very logic meant to detect the failure.",
	"A stuck discrete input can suppress multiple downstream faults indefinitely, and only present as a top-level fault e.g. command/enable signals.",
	"Some no-dispatch annunciations are driven by derived software state, not actual system status, leading to notoriously bothersome warnings.",
	"MEL relief for one system can silently disable another through shared validity logic, often requiring no secondary notice or deviation.",
	"Many fault monitoring systems become active only after the first wheel speed signal achieves a minimum value.",
	"Some air data systems declare validity based on time since power-up, not airflow.",
	"Electrical contactor arcing is often greatest, and cannot be reliably tested without, high-load transfer from a running engine generator.",
	"Parking brake switch bounce may create brake control faults due to excessively gentle application or release during pushback.",
	"Early faults in antiskid systems almost always correlate to high noise during pushback, the only time the sensors rotate in reverse.",
}

var memoryItems = []string{
	"The fault waits until pushback because it respects witnesses.",
	"If it survived three power cycles at the gate, it will fail immediately once in motion.",
	"The system only breaks after pushback to avoid paperwork.",
	"The fault is allergic to maintenance personnel within arm’s reach.",
	"The airplane knows when the tug disconnects.",
	"If the fault clears by lineup, it will return on climbout.",
	"The warning exists solely to prove redundancy is theoretical.",
	"The reset worked, but only spiritually.",
	"The system detected something wrong and chose silence.",
	"The failure is real, but temporary, and therefore your problem.",
	"This caution exists to meet certification, not reality.",
	"The airplane passed its self-test by lying.",
	"It worked yesterday, and under worse conditions.",
	"It fails after pushback because pilots are present.",
	"The MEL says \"procedure accomplished,\" not \"procedure works.\"",
	"The system is redundant, except when it isn't.",
	"Dispatch legality ends where reality begins.",
	"The MEL is technically correct and operationally cursed.",
	"The MEL assumes good judgment fills all gaps.",
	"The airplane is legal, but the crew is on their own.",
	"The author of the MEL never saw this fail in shitty weather.",
	"Dispatch is always permitted with *increased crew awareness.*",
	"The limitation satisfies lawyers, not aviators.",
	"The system may be **inop**, but the consequences are **acceptable.**",
	"It's deferrable because certification claimed it could be.",
	"Shutting down in a penalty box is the fastest way to open up your gate.",
	"The AOG part comes in tonight, on the airplane that also can't get airborne.",
	"The intermittent fault occurs just often enough to maintain plausibility.",
	"A fault often clears itself to avoid unnecessary documentation.",
	"Troubleshooting can often turn your one deferrable problem into two no-dispatch items.",
	"The AOG replacement fails the same way a majority of the time.",
}

var horseFacts = []string{
	"Horses can sleep standing up.",
	"A horse's teeth take up more space in their head than their brain.",
	"Horses can't vomit.",
	"The fastest recorded sprinting speed of a horse was 55 mph.",
	"Horses have nearly 360-degree vision.",
	"A horse's hoof is essentially a giant middle finger.",
	"Horses can run within hours of being born.",
	"The average horse heart weighs 9-10 pounds.",
	"Horses use facial expressions to communicate with each other.",
	"A horse can drink up to 10 gallons of water per day.",
	"Horses have the largest eyes of any land mammal.",
	"There are over 300 breeds of horses.",
	"Horses evolved from dog-sized creatures with multiple toes.",
	"A male horse has 40 teeth, females typically have 36.",
	"Horses can't breathe through their mouths.",
	"The original horse, Eohippus, was the size of a golden retriever.",
	"Horses have been domesticated for over 5,000 years.",
	"A horse's age can be estimated by examining its teeth.",
	"Horses produce approximately 10 gallons of saliva per day.",
	"The record for the longest horse jump is 28 feet.",
	"Horses have a strong fight-or-flight response.",
	"A horse's kneecap doesn't develop until they're 6 months old.",
	"Horses can't see directly in front of their faces.",
	"The scientific name for a horse is Equus caballus.",
	"Horses have excellent memories and can remember people for years.",
	"A newborn foal can stand within an hour of birth.",
	"Horses have 16 muscles in each ear.",
	"The oldest horse on record lived to be 62 years old.",
	"Horses can lock their legs to sleep standing without falling.",
	"A horse's hoof grows approximately 1/4 inch per month.",
	"Horses have a blind spot directly behind them.",
	"The fastest breed is generally considered to be the Thoroughbred.",
	"Horses can sense human emotions.",
	"A group of horses will not go to sleep at the same time.",
	"Horses can't burp.",
	"The tallest horse ever recorded was over 7 feet tall.",
	"Horses have the same number of bones as humans: 205.",
	"A horse's brain weighs about 2.5 pounds.",
	"Horses can get sunburned, especially on pink skin.",
	"The normal temperature for a horse is 99-101°F.",
	"Horses can recognize themselves in mirrors, making them one of the few animals with self-awareness.",
	"A horse's kick can generate up to 2,000 pounds of force per square inch.",
	"Horses have a third eyelid called a nictitating membrane that helps protect their eyes.",
	"The Przewalski's horse is the only truly wild horse species left in the world.",
	"Horses can't focus on objects closer than 4 feet in front of them.",
	"A horse's digestive system is approximately 100 feet long.",
	"Horses have a near-photographic memory for complex sequences.",
	"The 'frog' in a horse's hoof acts as a shock absorber and aids circulation.",
	"Horses can differentiate between dominant and submissive body language in humans.",
	"A horse's blood is approximately 10% of its body weight.",
	"Horses have been observed doing basic arithmetic in laboratory settings.",
	"The record for highest horse jump is 8 feet 1.25 inches.",
	"Horses are capable of recognizing familiar music, and one Derby winner's favorite genre was funk.",
	"Horses synchronize their heartbeats with their riders during calm activities.",
	"A horse's field of vision includes a blind spot the size of a small car directly in front.",
	"Horses can detect changes in barometric pressure hours before a storm.",
	"The average lifespan of a domestic horse is 25-30 years.",
	"Horses have more bones in their skeleton as foals than as adults due to fusion.",
	"A horse can run at 27 mph within 3 seconds of starting from standstill.",
	"Horses use their ears, eyes, and nostrils as a communication system with other horses.",
	"The smallest horse breed, the Falabella, typically stands under 32 inches tall.",
	"Horses have a 'sweet spot' behind their withers that triggers mutual grooming behavior.",
	"A horse's stomach only holds 2-4 gallons despite their large size.",
	"Horses can recognize and remember individual human faces for decades.",
	"The stripe down a horse's back is called a dorsal stripe and indicates primitive genetics.",
	"Horses have been documented grieving the loss of companions.",
	"A horse's neck contains only 7 vertebrae, the same as a giraffe or human.",
	"Horses pawing at the ground are actually investigating depth and texture.",
	"The fear of horses is called equinophobia.",
	"A horse once confided in me the truth at the center of our purpose in this universe.",
	"Horses require approximately 2 hours of REM sleep per day achieved in short bursts.",
	"A horse's whiskers are highly sensitive tactile sensors that shouldn't be trimmed.",
	"Horses can learn to use symbols to communicate their preferences to handlers.",
	"The natural gait of Icelandic horses includes a 'tölt' that keeps one foot always grounded.",
	"Horses have a vestigial toe bone called a splint bone from their multi-toed ancestors.",
	"A horse's coat color can change seasonally and with age, especially grays.",
	"Horses are capable of swimming and some breeds enjoy water.",
	"The 'Eohippus' or dawn horse was about the size of a fox terrier.",
	"Horses have a natural inclination to turn left, believed to be a brain hemisphere preference.",
	"A horse's gestation period is approximately 11 months.",
	"Horses can detect electromagnetic fields and use them for navigation.",
	"The star pattern on a horse's forehead is called a blaze and is genetically unique.",
	"Horses have been known to adopt orphaned foals from other mares.",
	"A horse's respiratory rate at rest is 8-15 breaths per minute.",
	"Horses in the wild travel an average of 20 miles per day grazing.",
	"The white sclera visible in a frightened horse's eye is called 'showing the white.'",
	"Horses can't cry emotional tears but do produce tears for eye lubrication.",
	"A horse's mane hair and tail hair grow continuously unlike body hair.",
	"Horses recognize the sound of their own names and respond differently than to other words.",
	"The feral Chincoteague ponies can drink saltwater due to adapted kidneys.",
	"Horses have an excellent sense of smell and use it to identify other horses.",
	"A horse's trust in humans can be measured by their willingness to lower their head.",
	"Horses rotate their ears 180 degrees independently to locate sounds.",
	"The Akhal-Teke breed has a metallic sheen to their coat due to unique hair structure.",
	"Horses can detect rider nervousness through changes in heart rate and sweat composition.",
	"A horse's cecum, part of the large intestine, holds up to 8 gallons.",
	"Horses have a pecking order in herds established through subtle body language.",
	"The average horse has a stride length of 12-15 feet at full gallop.",
	"Horses can distinguish between angry and happy human voices.",
	"A horse's hooves are made of the same protein as human fingernails: keratin.",
	"Horses establish 'bachelor bands' of young males before maturity in wild populations.",
	"The Morgan horse breed descended from a single stallion named Figure in the 1790s.",
}
